### ISSUE TITLE
EMAFilter does not name a type

### ISSUE THREAD

**Issue by TheSnowy0wl** [collin80/GEVCU6#10]
Hello,

I am attempting to upload the DEV GEVCU6 software into GEVCU6 Hardware.  However whenever I compile the GEVCU6.ino file into the hardware I receive an error in line 66 of BuiltinBMS.h 'EMAFilter' does not name a type.  Any help you can provide is appreciated!

Thanks.

**Comment by steveJM01** [comment]
Hi I , also, have same issue as described above... of 'EMAFilter' does not name a type.
I've uploaded missing Library files. but can not work out this problem.
Hope you can help
Thanks Steve

**Comment by collin80** [comment]
Be sure you're using the version of Microsmooth from my repo. It does have EMAFilter in it: https://github.com/collin80/Microsmooth
