### ISSUE TITLE
CAN Bus not working

### ISSUE THREAD

**Issue by bsculley** [collin80/GEVCU6#4]
I am having problems getting the GEVCU CAN bus to work.  I am using CAN0, with A2 as CANH0 and B2 as CANL0 on the 30 pin connector.  I have the PowerKey keyboard and a CAN monitoring board on the CAN network (both at 500000 baud).  I can see the CAN messages from the PowerKey, so I think the bus is functioning ok.

I put a log trace in at CanHandler::process, with the following results:

9246 - INFO: CAN: status=2162880 speed=500000
9247 - INFO: CAN: status=1151729664 speed=500000
9248 - INFO: CAN: status=2162880 speed=500000
9250 - INFO: CAN: status=1151729664 speed=500000

I have no way to interpret the status values.

I have tried simple hardware debugging: 

Resistance (unpowered) between CANH0->GND and CANL0->GND seems to be infinite (no reading) in both cases.

The voltage (powered, obviously)  between CANH0->GND and CANL0->GND is 0 in both cases.  All measurements are at the wires from the 30 pin connector.  I have verified that the multi-meter is working.  Other devices show nominal readings.

Don't know what I'm doing wrong.  Any ideas gratefully accepted.

**Comment by bsculley** [comment]
Further to this issue, I have tried using CAN1 with the same results.

**Comment by collin80** [comment]
With the CANH0 and CANL0 wires not connected to anything else what is the resistance between them? It should be 120 ohms. They're isolated floating differential wires you won't necessarily get good readings to ground. You can basically only read between them. It's been too long since I saw where those status flags even come from. I'll try to look that up.

**Comment by bsculley** [comment]
Thanks for the tip.  I get 120 ohms between the H/L lines when measured at the terminals on the GEVCU, however, I get nothing when measured at the ends of the wires on the cinch plug.  I have verified that it is seated as far as possible and, in fact, some other terminals are connected, e.g. A0.

 

I have gotten the CAN working by connecting some jumper wires directly to the terminals on the GEVCO.  I believe there is some defect in the cinch plug wiring or mechanics.

 

Bob
