### ISSUE TITLE
Failure to receive extended frames

### ISSUE THREAD

**Issue by bsculley** [collin80/GEVCU6#6]
Hi Collin,

I posted a parallel issue on the due_can repo.  I am not able to get the GEVCU to receive extended frames.  I tried the CAN_ExtendedPingPong example from the due_can library and was seeing the same result.  

I have done this in GEVCO.35.ino setup:

```
	for (int filter = 4; filter < 7; filter++) {
		Can0.setRXFilter(filter, 0, 0, true);
	}
```
and this in the setup of my custom motor controller:

`	canHandlerEv.attach(this, 0xF9, 0x1FFFFFFF, true);
`

Hopefully I'm just doing something wrong, but I sure can't see it.  I could use a boost here.

**Comment by bsculley** [comment]
Further to this issue, I have also tried using watchFor() in place of setting up explicit filters, but it had no effect.

**Comment by collin80** [comment]
I'm going to try to look into it further. The odd part is that I just
recently used a different board but with the same processor and CAN library
and it was receiving extended frames perfectly well.

**Comment by bsculley** [comment]
Never mind.  I was using the filter mask all wrong.  Sorry.
